#!/bin/bash

echo "⚙️ Formatting code with dart format..."
dart format .
STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo "🚫 dart format failed. Aborting commit."
  exit $STATUS
fi

echo "⚙️ Running lints..."
flutter analyze .
STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo "🚫 flutter analyze failed. Aborting commit."
  exit $STATUS
fi